<?xml version="1.0"?>

<robot name="nav_robot"
  xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="odom_plugin.xacro" />

  <gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">

      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${2*base_radius}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>

      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>

      <odom_publish_frequency>10</odom_publish_frequency>
      <topic>cmd_vel</topic>
      <robotBaseFrame>base_link</robotBaseFrame>

    </plugin>
  </gazebo>

  <gazebo reference="passive_wheel_front_link">
    <mu1 value="0.1" />
    <mu2 value="0.1" />
  </gazebo>

  <gazebo reference="passive_wheel_back_link">
    <mu1 value="0.1" />
    <mu2 value="0.1" />
  </gazebo>

  <gazebo>
    <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
      <topic>/joint_states</topic>
      <joint_name>left_wheel_joint</joint_name>
      <joint_name>right_wheel_joint</joint_name>
    </plugin>
  </gazebo>
</robot>